import Head from "next/head";
import Navbar from "../components/navbar/Navbar";
import Script from "next/script";
import Footer from "../components/footer/footer";
import AddsLaterales from "../components/adds/add";
import Header from "../components/header/header";
import Image from "next/image";
import TarjetaDerecha from "../components/tarjetas/tarjetaDerecha";
import TarjetasProyectos from "../components/tarjetas/TarjetasProyectos";
import VideoHome from "../components/videos/videoHome";
import Galeria from "../components/galería/galeria";
import CaracteristicasTarjetas from "../components/tarjetas/caracteristicasTarjetas";
import React, { useEffect } from "react";
import { Client } from "@notionhq/client";

export async function getStaticProps() {
  const notion = new Client({ auth: process.env.NOTION_API_KEY });

  const respuesta1 = await notion.databases.query({
    database_id: "8b30f650340c4170a4d7bd4c48d9784f",
    filter: {
      property: "web",
      checkbox: {
        equals: true,
      },
    },
  });
  const respuesta2 = await notion.databases.query({
    database_id: "7ced0ded2aec437a9b13b59cd18c2a96",
  });
  const respuesta3 = await notion.databases.query({
    database_id: "3fc6313684754f09802be2a6577f303a",
    filter: {
      property: "web",
      checkbox: {
        equals: true,
      },
    },
  });

  return {
    props: {
      dataProyectos: respuesta1.results,
      dataVideos: respuesta2.results,
      dataFotos: respuesta3.results,
    },
  };
}

export default function Home({ dataProyectos, dataVideos, dataFotos }) {
  useEffect(() => {
    console.log(dataVideos);
  });
  const videoPortada = dataVideos[0].properties.link.url;

  return (
    <div>
      <Head>
        <title>Streaming Pro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Script src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></Script>
        <Script src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></Script>

        <Navbar />
        <div className="m-20 z-10"></div>
        <div>
          <Header />
        </div>
        <div className="container">
          <TarjetaDerecha
            foto="/foto.jpeg"
            titulo="Bienvenidos a mi página Web"
            descripcion={
              <text>
                Soy Marcelo Remeseiro y tengo una pasión por la tecnología
                audiovisual.
                <br /> En mi canal de Youtube, comparto mis conocimientos y
                experiencias en el mundo del audio y video profesional, con
                énfasis en herramientas como OBS, vMix y Blackmagic. También
                hablo de todo lo relacionado con el streaming en vivo, desde la
                configuración de una transmisión hasta la producción de
                contenido de alta calidad.
                <br />
                Si te interesa el mundo del audio y video profesional, o si
                quieres aprender más sobre el streaming en vivo, no dudes en
                visitar mi canal de Youtube y suscríbete para recibir contenido
                actualizado. <br />
                ¡Me encantaría tenerte como parte de mi comunidad!
              </text>
            }
            firma="Marcelo Remeseiro"
            cargo="Technical Manager"
          />
          <TarjetasProyectos data={dataProyectos} />
          <VideoHome data={dataVideos} />
          <CaracteristicasTarjetas />
          <Galeria data={dataFotos} />
        </div>

        <Footer />
      </main>
    </div>
  );
}
