import Head from "next/head";
import Navbar from "../components/navbar/Navbar";
import Script from "next/script";
import Footer from "../components/footer/footer";
import AddsLaterales from "../components/adds/add";
import Header from "../components/header/header";
import Image from "next/image";
import TarjetaDerecha from "../components/tarjetas/tarjetaDerecha";
import { GridTarjetas } from "../components/tarjetas/gridTarjetas";
import VideoHome from "../components/videos/videoHome";
import Galeria from "../components/galería/galeria";
import CaracteristicasTarjetas from "../components/tarjetas/caracteristicasTarjetas";

export default function Home({ dataflex, dataSoloQ }) {
  return (
    <div>
      <Head>
        <title>Streaming Pro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Script src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></Script>
        <Script src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></Script>

        <Navbar />
        <div className="m-20 z-10"></div>
        <div>
          <Header />
        </div>
        <div className="container">
          <TarjetaDerecha
            foto="https://images.unsplash.com/photo-1499470932971-a90681ce8530?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80"
            titulo="Bienvenidos a mi página Web"
            descripcion={<text>Soy Marcelo Remeseiro y tengo una pasión por la tecnología audiovisual.<br/> En mi canal de Youtube, comparto mis conocimientos y experiencias en el mundo del audio y video profesional, 
            con énfasis en herramientas como OBS, vMix y Blackmagic. También hablo de todo lo relacionado con el streaming en vivo, desde la configuración de una transmisión hasta la producción de contenido de alta calidad.<br/>
            Si te interesa el mundo del audio y video profesional, o si quieres aprender más sobre el streaming en vivo, no dudes en visitar mi canal de Youtube y suscríbete para recibir contenido actualizado. <br/>¡Me encantaría tenerte como parte de mi comunidad!</text>}
            firma="Marcelo Remeseiro"
            cargo="Technical Manager"
          />
          <GridTarjetas />
          <VideoHome tituloVideo="Título del video" video={"https://www.youtube.com/embed/7VUcEoR9dI0"} />
          {/* <TarjetaDerecha 
            foto="https://images.unsplash.com/photo-1499470932971-a90681ce8530?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80"
            titulo="Bienvenidos a mi página Web"
            descripcion={<text>Soy Marcelo Remeseiro y tengo una pasión por la tecnología audiovisual.<br/> En mi canal de Youtube, comparto mis conocimientos y experiencias en el mundo del audio y video profesional, 
            con énfasis en herramientas como OBS, vMix y Blackmagic. También hablo de todo lo relacionado con el streaming en vivo, desde la configuración de una transmisión hasta la producción de contenido de alta calidad.<br/>
            Si te interesa el mundo del audio y video profesional, o si quieres aprender más sobre el streaming en vivo, no dudes en visitar mi canal de Youtube y suscríbete para recibir contenido actualizado. <br/>¡Me encantaría tenerte como parte de mi comunidad!</text>}
            firma="Marcelo Remeseiro"
            cargo="Technical Manager"/> */}
          <CaracteristicasTarjetas  />
          <Galeria />
        </div>

        <Footer />
      </main>
    </div>
  );
}
